modLoader="javafml"
loaderVersion="[4,)" #neoforge version dep
license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/Keymasterkid/Morph-V2/issues"

[[mods]]
    modId="morph"
    version="${file.jarVersion}" #mandatory
    displayName="Morph V2"
    displayURL="https://github.com/Keymasterkid/Morph-V2"
    authors="OG69 Dev™"
    description='''
    Kill other entities and take their form.
    '''


