modLoader="javafml"
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"
issueTrackerURL="https://github.com/Keymasterkid/Morph-V2/issues"

[[mods]]
    modId="morph"
    version="${mod_version}" #mandatory
    displayName="Morph V2"
    displayURL="https://github.com/Keymasterkid/Morph-V2"
    authors="OG69 Dev™"
    credits="Original Morph mod by iChun"
    description='''
    Kill other entities and take their form.
    '''

[[mods]]
    modId="ichunutil"
    version="0.3.0" #mandatory
    displayName="iChunUtil"
    authors="iChun, OG69 Dev™"
    description='''
    A library mod used by iChun''s mods.
    '''



[[mixins]]
config = "morph.mixins.json"
